version: "3.7"

volumes:
  burstvolume:
    name: burst-volume

networks:
  burstnetwork:
    name: burst-network

services:
  pg:
    image: postgres:13
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - burstvolume:/var/lib/postgresql/data
    networks:
      - burstnetwork
  burst:
    build:
      context: .
      args:
        API_PORT: ${API_PORT}
    env_file:
      - .env
    depends_on:
      - pg
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - burstnetwork
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]
